And/pe 128surveymonkey
proversity-org/openedx-surveymonkey-xblock pull request #1
Opened 2018-10-01 18:38 UTC by andrey-canon

## Description 
This branch contains the first version for SurveyMonkeyXblock, the files added are the following:
- surveymonkey.py -> Main file, variables methods and logic
- surveymonkey.html -> Html to be shown 
- surveymonkey.css-> Styles" Empty for now "
- surveymonkey.js -> Javascript code " Empty for now "
- setup.py -> contains version and requirements to run the xblock
- django.po -> The string to be translate (Only for french)

## Reviewers 
- [ ] @diegomillan 
- [ ] @ericfab179

2018-10-01 18:44 UTC, ericfab179 commented on surveymonkey/surveymonkey.py
> +"""TO-DO: Write a description of what this XBlock is."""
Please complete docstring.

2018-10-05 17:11 UTC, andrey-canon commented
@ericfab179 I have add the docstring.
@diegomillan  Please make the review

2018-10-05 18:16 UTC, ericfab179 approved these changes

2018-10-05 20:22 UTC, diegomillan requested changes

2018-10-05 20:22 UTC, diegomillan commented on README.md
> +-   If user tracking is selected, then the survey URL includes a `uuser_anonymous_id` custom var with the student's anonymous user id
Minor fix `user_anonymous_id`

2018-10-05 20:22 UTC, diegomillan commented on README.md
> +-   Clicking the survey link should open the survey in a new browser tab.
Should say: Clicking over the link opens the survey in a new browser tab

2018-10-05 20:22 UTC, diegomillan commented on README.md
> +-   I can define the text used to link to the survey (or leave it blank to use the default which should be “complete the survey”).
letś just say  "I  can define the text used to link to the survey (or leave it blank to use the default)"

2018-10-05 20:22 UTC, diegomillan commented on README.md
> +-   I can select to make the survey trackable (i.e. pass user id across via URL) - or not.
Please, Use choose instead of select

2018-10-05 20:22 UTC, diegomillan commented on README.md
> +The Openedx-Surveymonkey Xblock allows to embed a survey link inside a unit, also, allows to include the survey description and title. The xblock allows you to include the user anonymous id as a cust
extra `,` after results.

2018-10-09 15:40 UTC, andrey-canon commented on README.md
> +-   If user tracking is selected, then the survey URL includes a `uuser_anonymous_id` custom var with the student's anonymous user id
ok

2018-10-09 15:41 UTC, andrey-canon commented on README.md
> +-   Clicking the survey link should open the survey in a new browser tab.
ok

2018-10-09 15:41 UTC, andrey-canon commented on README.md
> +-   I can define the text used to link to the survey (or leave it blank to use the default which should be “complete the survey”).
ok

2018-10-09 15:42 UTC, andrey-canon commented on README.md
> +-   I can select to make the survey trackable (i.e. pass user id across via URL) - or not.
ok

2018-10-09 15:42 UTC, andrey-canon commented on README.md
> +The Openedx-Surveymonkey Xblock allows to embed a survey link inside a unit, also, allows to include the survey description and title. The xblock allows you to include the user anonymous id as a cust
ok

2018-10-09 15:43 UTC, andrey-canon commented
@diegomillan requested changes has been amended

2018-10-09 16:42 UTC, diegomillan approved these changes

2018-10-09 17:01 UTC, merged